#!/bin/bash

# Setup script to create .env file for Red Zone Dashboard

echo "🔧 Setting up Red Zone Dashboard environment..."

# Create .env file if it doesn't exist
if [ ! -f ".env" ]; then
    cat > .env << 'EOF'
# Red Zone Dashboard Environment Configuration
# Generated by setup_env.sh

# Flask Configuration
SECRET_KEY=red-zone-dashboard-secret-key-2024
FLASK_ENV=production

# Database Configuration (defaults to local SQLite)
DATABASE_URL=sqlite:///red_zone_analysis.db

# Integration Settings
ENABLE_REAL_ANALYSIS=true
EOF

    echo "✅ Created .env file"
else
    echo "⚠️  .env file already exists, skipping..."
fi

# Check if parent .env exists
if [ -f "../.env" ]; then
    echo "✅ Found parent .env file - dashboard will use it for Databricks/OpenAI settings"
else
    echo "⚠️  Parent .env not found at ../.env"
    echo "   The dashboard needs these variables in the parent .env:"
    echo "   - DATABRICKS_HOST"
    echo "   - DATABRICKS_HTTP_PATH"
    echo "   - DATABRICKS_TOKEN"
    echo "   - DATABRICKS_CATALOG"
    echo "   - DATABRICKS_SCHEMA"
    echo "   - OPENAI_API_KEY"
    echo "   - OPENAI_MODEL"
fi

echo ""
echo "🎯 Next steps:"
echo "1. Make sure parent .env has all required variables"
echo "2. Run: python dashboard.py"
echo "3. Visit: http://localhost:5000"
